version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - kafka
  
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"

  auth-app:
    image: auth
    container_name: auth-app
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/auth-db
      - KAFKA_BROKER=kafka:9092
      - EUREKA_SERVER_HOST=registry
      - EUREKA_SERVER_PORT=8888
    depends_on:
      - mongo
      - kafka
      - registry
      - gateway

  ms-group-app:
    image: msgroup
    container_name: ms-group-app
    ports:
      - "3002:3002"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ms-group
      - KAFKA_BROKER=kafka:9092
      - EUREKA_SERVER_HOST=registry
      - EUREKA_SERVER_PORT=8888
    depends_on:
      - mongo
      - kafka
      - registry  
      - gateway

  ms-filtrage-app:
    image: msfiltarge
    container_name: ms-filtrage-app
    ports:
      - "3006:3006"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ms-filtrage
      - KAFKA_BROKER=kafka:9092
      - EUREKA_SERVER_HOST=registry
      - EUREKA_SERVER_PORT=8888
    depends_on:
      - mongo
      - kafka
      - registry  
      - gateway

  ms-notification-app:
    image: msnotification
    container_name: ms-notification-app
    ports:
      - "3040:3040"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ms-notification
      - KAFKA_BROKER=kafka:9092
      - EUREKA_SERVER_HOST=registry
      - EUREKA_SERVER_PORT=8888
    depends_on:
      - mongo
      - kafka
      - registry  
      - gateway

  ms-forum-messagerie:
    image: msforummessagerie
    container_name: ms-forum-messagerie
    ports:
      - "3030:3030"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ms-forum-messagerie
    depends_on:
      - mongo

  ms-arabe-language:
    image: msarabeLanguage
    container_name: ms-arabe-language
    ports:
      - "8090:8090"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ms-arabe-language
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8888/eureka
    depends_on:
      - mongo
      - gateway  
      - registry

  gateway:
    image: gateway
    container_name: gateway
    ports:
      - "7777:7777"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ms-filtrage
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8888/eureka
    depends_on:
      - registry     

  registry:
    image: registry
    container_name: registry
    ports:
      - "8888:8888"

volumes:
  mongo-data:
