server:
  port: 7777

spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders: "*"


      routes:
        - id: route1
          predicates:
            - Path=/ms-group/**
          filters:
            - RewritePath=/ms-group/(?<s>.*), /${s}
          uri: lb://ms-group

        - id: route2
          predicates:
            - Path=/auth-service/**
          filters:
              - RewritePath=/auth-service/(?<s>.*), /${s}
          uri: lb://auth-service

        - id: route3
          predicates:
            - Path=/arabeLanguage/**
          filters:
            - RewritePath=/arabeLanguage/(?<s>.*), /${s}
          uri: lb://ms-ArabeLanguage

        - id: route4
          predicates:
            - Path=/ms-forumMessagerie/**
          filters:
            - RewritePath=/ms-forumMessagerie/(?<s>.*), /${s}
          uri: lb://ms-forumMessagerie

        - id: route5
          predicates:
            - Path=/ms-projection/**
          filters:
            - RewritePath=/ms-projection/(?<s>.*), /${s}
          uri: lb://ms-projection

        - id: route6
          predicates:
            - Path=/ms-notification/**
          filters:
            - RewritePath=/ms-notification/(?<s>.*), /${s}
          uri: lb://ms-notification

        - id: route7
          predicates:
            - Path=/ms-payment/**
          filters:
            - RewritePath=/ms-paymant/(?<s>.*), /${s}
          uri: lb://ms-payment



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka


